CREATE DATABASE MAGAZIN

CREATE TABLE CLIENT
(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	COD_CLIENT INT
)

CREATE TABLE OPERATOR
(
	OPERATOR_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	PRENUME VARCHAR(30),
	FUNCTIA VARCHAR(50),
	USERNAME VARCHAR(20),
	PASS VARCHAR(20),
	COD INT,
	TIP_ACCES INT
)

CREATE TABLE FACTURA_REC
(
	FACTURA_REC_ID INT PRIMARY KEY IDENTITY(1,1),
	NR_FACTURA INT,
	DATA_FACTURA DATE,
	EMITENT VARCHAR(50)
)

CREATE TABLE PRODUS
(
	PRODUS_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(40),
	COD_PRODUS INT,
	AUTOR VARCHAR(50),
	EDITURA VARCHAR(50),
	COLECTIA VARCHAR(50),
	AN_APARITIE INT,
	NR_PAG INT,
	LIMBA VARCHAR(5)
)

CREATE TABLE RECEPTIE
(
	RECEPTIE_ID INT PRIMARY KEY IDENTITY(1,1),
	PRODUS_ID INT FOREIGN KEY REFERENCES PRODUS(PRODUS_ID),
	FACTURA_REC_ID INT FOREIGN KEY REFERENCES FACTURA_REC(FACTURA_REC_ID),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	STOCK1 INT,
	STOCK2 INT,
	PRET_INTRARE DECIMAL(9,2),
	PRET_VANZARE DECIMAL(9,2),
)



CREATE TABLE FIRMA
(
	FIRMA_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(30),
	COD_FISCAL INT,
	ADRESA VARCHAR(50)
)

CREATE TABLE CEC
(
	CEC_ID INT PRIMARY KEY IDENTITY(1,1),
	OPERATOR_ID INT FOREIGN KEY REFERENCES OPERATOR(OPERATOR_ID),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	FIRMA_ID INT FOREIGN KEY REFERENCES FIRMA(FIRMA_ID),
	NR_CEC INT,
	DATA_CEC DATE,
	SUMA_CEC DECIMAL(9,2)
)

CREATE TABLE VANZARE
(
	VANZARE_ID INT PRIMARY KEY IDENTITY(1,1),
	CEC_ID INT FOREIGN KEY REFERENCES CEC(CEC_ID),
	RECEPTIE_ID INT FOREIGN KEY REFERENCES RECEPTIE(RECEPTIE_ID),
	CANTITATE INT,
	SUMA DECIMAL(9,2)
)

--POPULAREA

INSERT INTO OPERATOR(NUME,PRENUME,FUNCTIA,USERNAME,PASS,COD,TIP_ACCES)
VALUES('VOICU','DUMITRU','CASIER','VOICU123','123',' ',NULL),
		('CENTROI','ALEXANDRU','CASIER','CENTROIA','123',' ',NULL), 
		('MARDARI','ANA','ADMINISTRATOR','MARDARI12','12345',' ',NULL),
		('ILONICI','VASILE','DEPOZITAR','ILONICI4','1234',' ',NULL),
		('FEDER','ANTON','ADMINISTRATOR','FEDER_A','12345',' ',NULL)


INSERT INTO PRODUS(DENUMIRE,COD_PRODUS,AUTOR,EDITURA,COLECTIA,AN_APARITIE,NR_PAG,LIMBA)
VALUES('TOTUL SE TERMINA CU NOI','111','COLLEN HOOVER','EPICA','EPICLOVE',2018,416,'RO'),
('POVESTI CA SA TE IUBESTI MAI MULT','222','ALEX ROVIRA','HUMANITAS','JUNIOR',2021,176,'RO')

INSERT INTO PRODUS(DENUMIRE,COD_PRODUS,AUTOR,EDITURA,COLECTIA,AN_APARITIE,NR_PAG,LIMBA)
VALUES('LUCEAFARUL','333','MIHAI EMINESCU','LITERA','CLASIC',1997,200,'RO'),
       ('IT ENDS WITH US','444','COLLEN HOOVER','EPICA','EPICLOVE',2019,348,'EN')

INSERT INTO CLIENT(NUME,PRENUME,COD_CLIENT)
VALUES('STEPAN','ALEXEI',123),
      ('IDEL','STEFAN',112)

INSERT INTO FIRMA(NUME,COD_FISCAL,ADRESA)
VALUES('ELEEFANT','131242','ALEXANDRU CEL BUN 23/1'),
('CARTURESTI','5475606','STEFAN CEL MARE 93/5')


